"""Skill document generator in Claude Skills markdown format."""
from pathlib import Path
from jinja2 import Template

from ..models.entities import Skill, Task, TaskType


SKILL_TEMPLATE = """# Skill: {{ skill.name }}

## Purpose
{{ skill.purpose or "이 스킬이 해결하는 업무 목적을 정의합니다." }}

## Inputs
{% if skill.inputs %}
- required:
{% for key, value in skill.inputs.items() %}
  - {{ key }}: {{ value.get('type', 'string') }} - {{ value.get('description', '') }}
{% endfor %}
{% else %}
- 입력 데이터 없음
{% endif %}

## Outputs
{% if skill.outputs %}
{% for key, value in skill.outputs.items() %}
- {{ key }}: {{ value.get('type', 'string') }} - {{ value.get('description', '') }}
{% endfor %}
{% else %}
- 출력 데이터 없음
{% endif %}

## Preconditions
{% if skill.preconditions %}
{% for condition in skill.preconditions %}
- {{ condition }}
{% endfor %}
{% else %}
- 없음
{% endif %}

## Procedure
{% if skill.procedure %}
{% for step in skill.procedure %}
{{ loop.index }}. {{ step }}
{% endfor %}
{% else %}
1. 작업을 시작합니다.
2. 필요한 데이터를 수집합니다.
3. 처리를 수행합니다.
4. 결과를 반환합니다.
{% endif %}

## Exceptions & Handling
{% if skill.exceptions %}
{% for exception in skill.exceptions %}
- {{ exception }}
{% endfor %}
{% else %}
- 예외 발생 시 상위 프로세스에 보고
{% endif %}

## Tools
{% if skill.tools %}
{% for tool in skill.tools %}
- {{ tool }}
{% endfor %}
{% else %}
- 없음
{% endif %}

## Evidence
{% if evidences %}
{% for evidence in evidences %}
- doc_id: {{ evidence.doc_id }} / page: {{ evidence.page }} / {{ evidence.text_span[:100] }}...
{% endfor %}
{% else %}
- 근거 문서 정보 없음
{% endif %}

---
*Generated by PDF2BPMN*
"""


class SkillGenerator:
    """Generate Claude Skills markdown documents from tasks."""
    
    def __init__(self):
        self.template = Template(SKILL_TEMPLATE)
    
    def generate_from_task(
        self,
        task: Task,
        evidences: list = None
    ) -> tuple[Skill, str]:
        """Generate skill document from a task."""
        
        # Create skill from task
        skill = Skill(
            name=f"{task.name} Skill",
            summary=task.description,
            purpose=task.description or f"{task.name} 태스크를 수행합니다.",
            inputs={},
            outputs={},
            preconditions=[],
            procedure=self._extract_procedure(task.description),
            exceptions=["오류 발생 시 재시도", "실패 시 상위 보고"],
            tools=[]
        )
        
        # Generate markdown
        markdown = self.template.render(
            skill=skill,
            evidences=evidences or []
        )
        
        return skill, markdown
    
    def generate(
        self,
        skill: Skill,
        evidences: list = None
    ) -> str:
        """Generate markdown from skill object."""
        return self.template.render(
            skill=skill,
            evidences=evidences or []
        )
    
    def _extract_procedure(self, description: str) -> list[str]:
        """Extract procedure steps from description."""
        if not description:
            return ["작업을 수행합니다."]
        
        # Split by common delimiters
        steps = []
        
        # Try numbered steps
        import re
        numbered = re.findall(r'\d+[.)\s]+(.+?)(?=\d+[.)\s]|$)', description)
        if numbered:
            return [s.strip() for s in numbered if s.strip()]
        
        # Try bullet points
        bullets = re.findall(r'[-•]\s*(.+?)(?=[-•]|$)', description)
        if bullets:
            return [s.strip() for s in bullets if s.strip()]
        
        # Split by sentences
        sentences = re.split(r'[.。]\s*', description)
        steps = [s.strip() for s in sentences if s.strip() and len(s) > 5]
        
        if not steps:
            steps = [description[:200] + "..." if len(description) > 200 else description]
        
        return steps[:10]  # Limit to 10 steps
    
    def generate_all_skills(
        self,
        tasks: list[Task],
        output_dir: str
    ) -> dict[str, str]:
        """Generate skill documents for all agent tasks."""
        
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        skill_docs = {}
        
        for task in tasks:
            # Only generate skills for agent-type tasks
            if task.task_type == TaskType.AGENT:
                skill, markdown = self.generate_from_task(task)
                
                # Create safe filename
                safe_name = "".join(c if c.isalnum() or c in "._-" else "_" for c in task.name)
                filename = f"{safe_name}.skill.md"
                filepath = output_path / filename
                
                filepath.write_text(markdown, encoding="utf-8")
                skill_docs[task.task_id] = str(filepath)
                
                # Update skill with path
                skill.md_path = str(filepath)
        
        return skill_docs
    
    def save(self, markdown: str, output_path: str) -> str:
        """Save skill markdown to file."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(markdown, encoding="utf-8")
        return str(path)




